name: Publish

on:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Needed for npm provenance
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org/'

      - run: npm ci

      - run: npm run build

      - run: npm run lint

      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_MCP_WRITE }}

  publish-mcp:
    runs-on: ubuntu-latest
    needs: publish-npm
    permissions:
      id-token: write  # Required for GitHub OIDC authentication
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Sync version in server.json
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          node -e "const fs=require('fs');const s=JSON.parse(fs.readFileSync('server.json'));s.version='$VERSION';s.packages[0].version='$VERSION';fs.writeFileSync('server.json',JSON.stringify(s,null,2)+'\n')"

      - name: Install MCP Publisher
        run: |
          curl -L "https://github.com/modelcontextprotocol/registry/releases/latest/download/mcp-publisher_$(uname -s | tr '[:upper:]' '[:lower:]')_$(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/').tar.gz" | tar xz mcp-publisher

      - name: Login to MCP Registry
        run: ./mcp-publisher login github-oidc

      - name: Publish to MCP Registry
        run: ./mcp-publisher publish